[tool.briefcase]
project_name = "Paper"
bundle = "com.techwood.paper"
version = "0.0.1"
url = "https://paper.techwood.com/paper"
license = "GNU General Public License v3 (GPLv3)"
author = 'techwood'
author_email = "dev.rubbie@gmail.com"

[tool.briefcase.app.paper]
formal_name = "Paper"
description = "collaborative checklist mananger"
icon = "src/paper/resources/paper"
sources = ['src/paper']
requires = [
    'PySide2==6.0.1',
    'requests==2.25.1'
]


[tool.briefcase.app.paper.macOS]
requires = []

[tool.briefcase.app.paper.linux]
requires = []
system_requires = []

[tool.briefcase.app.paper.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.paper.iOS]
requires = []

[tool.briefcase.app.paper.android]
requires = []
